name: Action Sorteador
run-name: ${{ github.actor }} is my first GitHub Actions 🤩
on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: "AKIAXDQM7MX2RKLXHJSM"
        aws-secret-access-key: "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"
        aws-region: us-east-1

    - name: Deploy static site to S3 bucket
      run: aws s3 sync ./public/ s3://BUCKET_NAME --delete

